
services:

  backend:
    build:
      context: ./backend-ai
    container_name: engagex-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env

  customer:
    build:
      context: ./customer-app
    container_name: engagex-customer
    restart: always
    ports:
      - "3000:80"

  dashboard:
    build:
      context: ./frontend
    container_name: engagex-dashboard
    restart: always
    ports:
      - "3001:80"