"""
Seeds the 'Find Your Product' poll campaign.

Only the category question is stored here -- the 2 follow-up questions
are generated by AI on the fly, tailored to whichever category the user
picks, so they never need reseeding when categories change.

Run after schema.sql and campaign_schema.sql have been applied.
"""

import asyncio
import json
import os
import asyncpg
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:yourpassword@localhost:5432/engagex_db"
)


async def seed_poll():
    conn = await asyncpg.connect(DATABASE_URL)

    try:
        async with conn.transaction():
            campaign_id = await conn.fetchval(
                """
                INSERT INTO campaigns (title, description, campaign_type, reward_type,
                                         reward_value, target_context, end_date, slug)
                VALUES ($1, $2, $3, $4, $5, $6, NOW() + INTERVAL '30 days', $7)
                RETURNING id
                """,
                "Find Your Product",
                "Tell us what you're shopping for and we'll pick the right product for you.",
                "poll",
                None,   # no reward mechanic for this campaign
                None,
                "global",
                "skin-profile-quiz",
            )
            print(f"Created campaign id={campaign_id}")

            q1_id = await conn.fetchval(
                """
                INSERT INTO campaign_questions
                    (campaign_id, question_text, question_type, options, order_index)
                VALUES ($1, $2, $3, $4, $5)
                RETURNING id
                """,
                campaign_id,
                "Which category are you shopping for?",
                "category_select",
                json.dumps([]),  # populated live from /products/categories
                0,
            )
            print(f"  Question 1 (id={q1_id}): category select (dynamic)")
            print("  Questions 2-3: generated by AI per category (not stored)")

            print("Poll seeded successfully.")

    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(seed_poll())